/**
 * data-overrides/card_additions.json — full SupportCardRecord entries for
 * Global-released cards the pinned upstream does not carry yet (upstream-pin
 * lag, docs/provenance.md §3.2). Unlike *_overrides.json (which PATCH
 * generated records and fail on unknown ids), additions INSERT whole records;
 * they are merged before overrides so overrides can still patch them.
 *
 * Records are generated by the documented one-off scripts/extract-card-additions.ts
 * (node:sqlite over the spikes Global master.mdb) and committed — the build
 * stays reproducible from borrowed files + this checked-in JSON (P5).
 * Delete entries when the upstream pin catches up (the duplicate-id check
 * below turns a stale addition into a build error).
 */
import { existsSync } from 'node:fs';
import type { CardSkill, SupportCardRecord } from '@/core/types';
import { readJson } from './io';

export interface CardAdditionsFile {
  _comment?: string;
  records: SupportCardRecord[];
}

const CARD_RARITIES = new Set(['R', 'SR', 'SSR']);
const CARD_TYPES = new Set(['speed', 'stamina', 'power', 'guts', 'wit', 'friend', 'group']);
const SOURCE_TYPES = new Set(['chain', 'hint_pool', 'random_event', 'date_event']);

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** Deep-copy with documentation keys ('_'-prefixed) stripped (same convention as merge-overrides). */
function stripMeta<T>(value: T): T {
  if (Array.isArray(value)) return value.map(stripMeta) as T;
  if (isPlainObject(value)) {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value)) {
      if (!k.startsWith('_')) out[k] = stripMeta(v);
    }
    return out as T;
  }
  return value;
}

function validateAddition(
  record: SupportCardRecord,
  releasedSkillIds: ReadonlySet<string>,
  problems: string[],
): void {
  const where = `card_additions record "${record.cardId}"`;
  const fail = (msg: string): void => {
    problems.push(`${where}: ${msg}`);
  };

  if (typeof record.cardId !== 'string' || !/^\d+$/.test(record.cardId)) fail('cardId must be a numeric string');
  if (typeof record.nameEn !== 'string' || record.nameEn.length === 0) fail('nameEn missing');
  if (typeof record.charName !== 'string' || record.charName.length === 0) fail('charName missing');
  if (!CARD_RARITIES.has(record.rarity)) fail(`bad rarity "${record.rarity}"`);
  if (!CARD_TYPES.has(record.type)) fail(`bad type "${record.type}"`);
  if (record.server !== 'global') fail(`server must be "global", got "${String(record.server)}" (P4)`);
  if (typeof record.dataVersion !== 'string' || record.dataVersion.length === 0) fail('dataVersion missing');

  if (!Array.isArray(record.perLevel) || record.perLevel.length !== 5) {
    fail('perLevel must have exactly 5 entries (LB 0-4)');
  } else {
    record.perLevel.forEach((p, i) => {
      if (p.limitBreak !== i) fail(`perLevel[${i}].limitBreak must be ${i}`);
      for (const key of ['hintFrequency', 'hintLevels', 'specialtyPriority'] as const) {
        if (typeof p[key] !== 'number' || p[key] < 0) fail(`perLevel[${i}].${key} must be a number >= 0`);
      }
    });
  }

  if (!Array.isArray(record.skills)) {
    fail('skills must be an array');
    return;
  }
  for (const skill of record.skills as CardSkill[]) {
    if (!SOURCE_TYPES.has(skill.sourceType)) fail(`skill ${skill.skillId}: bad sourceType "${skill.sourceType}"`);
    if (typeof skill.skillId !== 'string' || !releasedSkillIds.has(skill.skillId)) {
      fail(`skill ${skill.skillId}: not a Global-released skill id (P4)`);
    }
    if (skill.hintLevels !== undefined) {
      if (skill.sourceType !== 'hint_pool') fail(`skill ${skill.skillId}: hintLevels is hint_pool-only`);
      if (typeof skill.hintLevels !== 'number' || skill.hintLevels < 1) {
        fail(`skill ${skill.skillId}: hintLevels must be a number >= 1`);
      }
    }
  }
  const poolCount = record.skills.filter((s) => s.sourceType === 'hint_pool').length;
  if (record.hintPoolSize !== poolCount) {
    fail(`hintPoolSize ${record.hintPoolSize} != hint_pool entry count ${poolCount}`);
  }
}

/**
 * Load, strip `_`-doc keys, and schema-validate the additions file.
 * Returns [] when the file does not exist (the mechanism is optional).
 * Throws (aggregated) on any schema violation, duplicate id within the file,
 * or collision with an id the generator already emitted.
 */
export function loadCardAdditions(
  path: string,
  opts: { existingCardIds: ReadonlySet<string>; releasedSkillIds: ReadonlySet<string> },
): SupportCardRecord[] {
  if (!existsSync(path)) return [];
  const parsed = readJson<CardAdditionsFile>(path);
  if (!Array.isArray(parsed.records)) {
    throw new Error('card_additions.json: "records" must be an array of full SupportCardRecord entries');
  }

  const problems: string[] = [];
  const seen = new Set<string>();
  const records = parsed.records.map((raw) => stripMeta(raw));
  for (const record of records) {
    validateAddition(record, opts.releasedSkillIds, problems);
    if (seen.has(record.cardId)) problems.push(`card_additions record "${record.cardId}": duplicate id in file`);
    seen.add(record.cardId);
    if (opts.existingCardIds.has(record.cardId)) {
      problems.push(
        `card_additions record "${record.cardId}": already emitted by the generator — ` +
          'the upstream pin caught up; delete this addition (provenance §3.2).',
      );
    }
  }
  if (problems.length > 0) {
    throw new Error(`card_additions.json failed validation:\n  ${problems.join('\n  ')}`);
  }
  return records;
}
